name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  AWS_REGION: us-east-2
  AWS_ROLE: arn:aws:iam::934979133063:role/CommonCicd-RootGitHubGithubPublishE17A1812-11JO1N1X1SZ1Y

jobs:
  publish:
    name: Publish Libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - run: npm run login:npm
      - run: npm install

      - name: Build latest 'ace'
        run: |
          cd packages/ace
          npm run build
          cd ../..
          npm install

      - run: npm run build
      - run: npm run checks

      - name: Publish Package Changesets
        id: changesets
        uses: changesets/action@v1
        with:
          commit: Publish new packages
          publish: npm run publish-packages
          title: Publish new packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
